[package]
name = "rust-python-demo"
version = "0.1.0"
authors = ["Benjamin Elder <ben.the.elder@gmail.com>"]
repository = "https://github.com/BenTheElder/rust-python-demo.git"
description = "demo of rust dynamic library"
license = "MIT"


[lib]
name = "demo"
path = "demo.rs"
crate-type = ["dylib"]